spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/blog_engine?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&amp&serverTimezone=Europe/Moscow
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(eG0r4FT1dPNlYKFt8C0cdQ==)
    password: ENC(xbkrb8StJMl8a+LzQXS2iJykT9wSEcfx)
  flyway:
    baseline-on-migrate: true
blog:
  title: DevPub
  subtitle: Блог разработчика
  phone: +7 989 195-23-09
  email: ivan_zukkel@mail.ru
  copyright: Зуккель Иван
  copyrightFrom: 2021
server:
  port: 8081
  base_url: http://localhost:8081
mailjet:
  mail:
    key: ENC(DNVszMtuQ5agS7APJ9XdIUsV9uF7YvUMudy6ulvaQKlGC8+tZlTFTtelwJV80EZz)
    secret: ENC(oq8vsQrtMEX9hNYwfUjy3gwZIubjjd+2tccsK3jQKq+fqNDXZzizK+aRH7GuY107)
    from: ENC(umHEhd3xewaiif6GsHZOkVV2c5xBu5lR5UHXCzXb2+9th0TzHRFm9A==)
jasypt:
  encryptor:
    bean: encryptorBean
