spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://${MYSQL_HOST:localhost}:3306/blog_engine?createDatabaseIfNotExist=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Kpim1993
  flyway:
    baseline-on-migrate: true

blog:
  title: DevPub
  subtitle: Блог разработчика
  phone: +7 989 195-23-09
  email: ivan_zukkel@mail.ru
  copyright: Зуккель Иван
  copyrightFrom: 2021